## Importação de Bibliotecas

In [2]:
import numpy as np

## Definição de Funções

In [3]:
def suporte(lista_in):
    ''' lista_in é uma matriz de entrada de tamanho m x n, com valor máximo de v
    lista_out é uma matriz de saída de tamanho 1 x v com o suporte do v-ésimo elemento
    '''
    
    # Valor maximo da lista
    lista_max = lista_in.flat[lista_in.argmax()]
    
    # funcao suporte
    lista_out = np.eye(lista_max+1)[lista_in].sum(axis=1)[:,1:].sum(axis=0)/len(lista_in)
    
    return lista_out

## Processamento da Lista

In [8]:
lista = np.array([[1,3,4,2],
                  [2,5,6,7],
                  [1,2,7,8],
                  [4,5,6,7]])

print('Lista de Entrada:\n', lista)

# codificar nomes -> números
# ajusta lista

suporte_lista = suporte(lista)

print('\nSuporte da Lista:\n', suporte_lista)

Lista de Entrada:
 [[1 3 4 2]
 [2 5 6 7]
 [1 2 7 8]
 [4 5 6 7]]

Suporte da Lista:
 [ 0.5   0.75  0.25  0.5   0.5   0.5   0.75  0.25]


## Encontrar Regras