In [42]:
import numpy as np
import scipy

## Variáveis Numéricas

### Normalização

#### Min-Max

In [10]:
a = np.array([0, 1, 2, 3, 4])
a_norm = (a-a.min())/(a.max()-a.min())
a_norm

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

#### Z-score

In [18]:
#usando scipy
from scipy import stats
a_zscore = stats.zscore(a)
print(a_zscore)

#usando numpy
a_zscore2 = (a - a.mean())/a.std()
print(a_zscore2)

# este método garante que a média vai ser zero e a variância, um.
print(a_zscore.mean())
print(a_zscore.var())

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
0.0
1.0


Distância Euclidiana: menor distância entre dois pontos

Distância de Manhattan: soma da variação em x com a variação em y (forma um triângulo com a distância euclidiana)

Quando há variação apenas em um dos eixos (reta vertical ou horizontal), as duas distâncias são as mesmas

### Distâncias

#### Exercício 2

Dados P = (-1,3, -2); Q = (-4,5,-2); R = (4, -1, 0); S = (7,0,1)

a) Achar o centróide dos pontos P,Q,R,S
b) Distância Euclidiana e de Manhattan de PQ, RS, QS

In [46]:
P = np.array([-1,3,-2])
Q = np.array([-4,5,-2])
R = np.array([4,-1,0])
S = np.array([7,0,1])

# item a
centroide = np.array([(P[0]+Q[0]+R[0]+S[0])/4, (P[1]+Q[1]+R[1]+S[1])/4, (P[2]+Q[2]+R[2]+S[2])/4])
centroide

# item b

np.mod(P[1],1000)

euclidiana_PQ = np.linalg.norm(P-Q)
print(euclidiana_PQ)

euclidiana_RS = np.linalg.norm(R-S)
print(euclidiana_RS)

euclidiana_QS = np.linalg.norm(Q-S)
print(euclidiana_QS)


manhattan_PQ = scipy.spatial.distance.cityblock(P,Q)
print(manhattan_PQ)


manhattan_RS = scipy.spatial.distance.cityblock(R,S)
print(manhattan_RS)


manhattan_QS = scipy.spatial.distance.cityblock(Q,S)
print(manhattan_QS)

3.60555127546
3.31662479036
12.449899598
5
5
19


Observa-se que a distância de Manhattan é sempre maior (ou igual) que a Euclidiana

## Variáveis binárias